name: Azure Function App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    name: Deploy Backend (Function App)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: cosmosdb-crud-app/api
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'crud-db-standard'
          package: 'cosmosdb-crud-app/api'
          publish-profile: ${{ secrets.FUNCTION_APP_PUBLISH_PROFILE }}
